### ISSUE TITLE
Add JavaScript Based projects....

### ISSUE THREAD

**Issue by cool-as-code** [cool-as-code/JavaScriptBasedProject#1]

**Comment by iamakhileshmishra** [comment]
I would like to contribute on this please assign this to me

**Comment by cool-as-code** [comment]
Sure @iamakhileshmishra 
Keep Coding :)

**Comment by cool-as-code** [comment]
Thanks for the quick  commit I will check this and merge it till then you could work on other project too.

**Comment by Ankitv003** [comment]
can i add a digital buisness card i made using react?

**Comment by cool-as-code** [comment]
Ya sure @Ankitv003 Go ahead and follow contribution guidelines :)
Keep Hacking 👍

**Comment by Vidhanvyrs** [comment]
hey @cool-as-code   can i add a whack-a-mole game that i developed in this hacktoberfest month

**Comment by cool-as-code** [comment]
Cool :) 
@Vidhanvyrs Go Ahead I am assigning this to you :)

**Comment by cool-as-code** [comment]
@Ankitv003 @Vidhanvyrs @iamakhileshmishra Do not forgot to give a Star to the repository :)

**Comment by Vidhanvyrs** [comment]
hey @cool-as-code have added the PR please have a look😊🙇‍♂️
