### ISSUE TITLE
API based projects

### ISSUE THREAD

**Issue by iamakhileshmishra** [cool-as-code/JavaScriptBasedProject#3]

**Comment by cool-as-code** [comment]
Well Done @iamakhileshmishra :)

**Comment by Vidhanvyrs** [comment]
hey @cool-as-code  i did a project that uses Recharts and hence added firebase to that project can i add it under this issue

**Comment by cool-as-code** [comment]
@Vidhanvyrs I have assigned you another issue #1 Please work on that first :)
